# Generated by Django 5.2.4 on 2025-07-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='avatar',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
