# Generated by Django 5.2.4 on 2025-07-16 03:30

import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_perfil_avatar_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='avatares/avatar_futbol.jpg', null=True, upload_to=tienda.models.avatar_upload_path),
        ),
    ]
